name: Build and Run
'on':
  - push
  - pull_request
jobs:
  build:
    strategy:
      matrix:
        configuration:
          - Debug
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Run the App
        run: dotnet run -p ../DataSender.cs

